// const votes = [
  
// // University Town Fine Food
//   {
//     title: "Fishball Noodles",
//     location: "University Town Fine Food",  
//     createdOn: new Date(),
//     percen: 0,
//     key: 1, 
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Yong Tau Foo",
//     location: "University Town Fine Food",
//     createdOn: new Date(),
//     percen: 0,
//     key: 2,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Thai Food",
//     location: "University Town Fine Food",
//     createdOn: new Date(),
//     percen: 0,
//     key: 3,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Korean Food",
//     location: "University Town Fine Food",
//     createdOn: new Date(),
//     percen: 0,
//     key: 4,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Muslim Food",
//     location: "University Town Fine Food",
//     createdOn: new Date(),
//     percen: 0,
//     key: 5,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Dim Sum",
//     location: "University Town Fine Food",
//     createdOn: new Date(),
//     percen: 0,
//     key: 6,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "La Mian",
//     location: "University Town Fine Food",
//     createdOn: new Date(),
//     percen: 0,
//     key: 7,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },

// // University Town Food Clique
//   {
//     title: "Japanese Food",
//     location: "University Town Food Clique",
//     createdOn: new Date(),
//     percen: 0,
//     key: 8,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Astons",
//     location: "University Town Food Clique",
//     createdOn: new Date(),
//     percen: 0,
//     key: 9,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Cai Fan",
//     location: "University Town Food Clique",
//     createdOn: new Date(),
//     percen: 0,
//     key: 10,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Ban Mian",
//     location: "University Town Food Clique",
//     createdOn: new Date(),
//     percen: 0,
//     key: 11,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Si Chuan",
//     location: "University Town Food Clique",
//     createdOn: new Date(),
//     percen: 0,
//     key: 12,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },

// // Faculty of Arts & Social Science (The Deck)
//   {
//     title: "Chicken Rice",
//     location: "Faculty of Arts & Social Science - The Deck",
//     createdOn: new Date(),
//     percen: 0,
//     key: 13,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Claypot",
//     location: "Faculty of Arts & Social Science - The Deck",
//     createdOn: new Date(),
//     percen: 0,
//     key: 14,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Yong Tau Foo",
//     location: "Faculty of Arts & Social Science - The Deck",
//     createdOn: new Date(),
//     percen: 0,
//     key: 15,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Ma La",
//     location: "Faculty of Arts & Social Science - The Deck",
//     createdOn: new Date(),
//     percen: 0,
//     key: 15,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Noodles Stall",
//     location: "Faculty of Arts & Social Science - The Deck",
//     createdOn: new Date(),
//     percen: 0,
//     key: 16,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Pizza Hut",
//     location: "Faculty of Arts & Social Science - The Deck",
//     createdOn: new Date(),
//     percen: 0,
//     key: 17,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },

// // Faculty of Science (Air-con)
//   {
//     title: "Taiwan Food",
//     location: "Faculty of Science (Air-con)",
//     createdOn: new Date(),
//     percen: 0,
//     key: 18,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Drink Stall",
//     location: "Faculty of Science (Air-con)",
//     createdOn: new Date(),
//     percen: 0,
//     key: 19,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Pasta Express",
//     location: "Faculty of Science (Air-con)",
//     createdOn: new Date(),
//     percen: 0,
//     key: 20,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },

// // Faculty of Science (Frontier)
//   {
//     title: "Noodles",
//     location: "Faculty of Science - Frontier",
//     createdOn: new Date(),
//     percen: 0,
//     key: 21,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Chicken Rice Stall",
//     location: "Faculty of Science - Frontier",
//     createdOn: new Date(),
//     percen: 0,
//     key: 22,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Western Food",
//     location: "Faculty of Science - Frontier",
//     createdOn: new Date(),
//     percen: 0,
//     key: 23,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Fruits Stall",
//     location: "Faculty of Science - Frontier",
//     createdOn: new Date(),
//     percen: 0,
//     key: 24,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Dessert Stall",
//     location: "Faculty of Science - Frontier",
//     createdOn: new Date(),
//     percen: 0,
//     key: 25,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Korean Stall",
//     location: "Faculty of Science - Frontier",
//     createdOn: new Date(),
//     percen: 0,
//     key: 26,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },
//   {
//     title: "Japanese Stall",
//     location: "Faculty of Science - Frontier",
//     createdOn: new Date(),
//     percen: 0,
//     key: 27,
//     star1: 0,
//     star2: 0,
//     star3: 0,
//     star4: 0,
//     star5: 0,
//     count: 0,
//     star_sum: 0
//   },

// ]

// // Collections.update to ensure no repeats
// _.each(votes, function(vote) {
//   Votes.update({key: vote.key}, {$set: vote}, {upsert: true});
// });


