const votes = [
  // University Town Fine Food
  {
    title: "Noodles",
    location: "University Town Fine Food",  
    short: "ff",
    createdOn: new Date(),
    percen: 0,
    key: 1, 
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Yong Tau Foo",
    location: "University Town Fine Food",
    short: "ff",
    createdOn: new Date(),
    percen: 0,
    key: 2,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Thai Food",
    location: "University Town Fine Food",
    short: "ff",
    createdOn: new Date(),
    percen: 0,
    key: 3,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Korean Food",
    location: "University Town Fine Food",
    short: "ff",
    createdOn: new Date(),
    percen: 0,
    key: 4,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Muslim Food",
    location: "University Town Fine Food",
    short: "ff",
    createdOn: new Date(),
    percen: 0,
    key: 5,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Dim Sum",
    location: "University Town Fine Food",
    short: "ff",
    createdOn: new Date(),
    percen: 0,
    key: 6,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "La Mian",
    location: "University Town Fine Food",
    short: "ff",
    createdOn: new Date(),
    percen: 0,
    key: 7,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },

  // University Town Food Clique
  {
    title: "Japanese",
    location: "University Town Food Clique",
    short: "fc",
    createdOn: new Date(),
    percen: 0,
    key: 8,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Astons",
    location: "University Town Food Clique",
    short: "fc",
    createdOn: new Date(),
    percen: 0,
    key: 9,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Cai Fan",
    location: "University Town Food Clique",
    short: "fc",
    createdOn: new Date(),
    up: 0,
    down: 0,
    percen: 0,
    key: 10,
    total: 0,
    stars: 0
  },
  {
    title: "Ban Mian",
    location: "University Town Food Clique",
    short: "fc",
    createdOn: new Date(),
    percen: 0,
    key: 11,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Si Chuan",
    location: "University Town Food Clique",
    short: "fc",
    createdOn: new Date(),
    percen: 0,
    key: 12,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },

  // Faculty of Arts & Social Science (The Deck)
  {
    title: "Chicken Rice",
    location: "Faculty of Arts & Social Science - The Deck",
    short: "deck",
    createdOn: new Date(),
    percen: 0,
    key: 13,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: " Claypot",
    location: "Faculty of Arts & Social Science - The Deck",
    short: "deck",
    createdOn: new Date(),
    percen: 0,
    key: 14,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Yong Tau Foo",
    location: "Faculty of Arts & Social Science - The Deck",
    short: "deck",
    createdOn: new Date(),
    percen: 0,
    key: 15,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },
  {
    title: "Ma La",
    location: "Faculty of Arts & Social Science - The Deck",
    short: "deck",
    createdOn: new Date(),
    up: 0,
    down: 0,
    percen: 0,
    key: 15,
    total: 0,
    stars: 0
  },
  {
    title: "Noodles",
    location: "Faculty of Arts & Social Science - The Deck",
    short: "deck",
    createdOn: new Date(),
    percen: 0,
    key: 16,
    star1: 0,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    count: 0,
    star_sum: 0
  },

]

// Collections.update to ensure no repeats
_.each(votes, function(vote) {
  Votes.update({key: vote.key}, {$set: vote}, {upsert: true});
});


